import type { BlueprintGraph } from '../types';

/**
 * Minimal blueprint graph matching the shape returned by the mock server.
 * DAG: A → B → D, A → C → E, {D, E} → F
 */
export const mockGraph: BlueprintGraph = {
  id: 'bp_test',
  tenant_id: '1',
  name: 'Test Blueprint',
  description: '',
  edges: [
    { source: 'node-a', target: 'node-b' },
    { source: 'node-a', target: 'node-c' },
    { source: 'node-b', target: 'node-d' },
    { source: 'node-c', target: 'node-e' },
    { source: 'node-d', target: 'node-f' },
    { source: 'node-e', target: 'node-f' },
  ],
  nodes: [
    {
      id: 'node-a',
      type: 'form',
      position: { x: 0, y: 0 },
      data: {
        id: 'bp_a',
        component_key: 'node-a',
        component_type: 'form',
        component_id: 'form-schema-ab',
        name: 'Form A',
        prerequisites: [],
        permitted_roles: [],
        input_mapping: {},
        sla_duration: { number: 0, unit: 'minutes' },
        approval_required: false,
        approval_roles: [],
      },
    },
    {
      id: 'node-b',
      type: 'form',
      position: { x: 200, y: 0 },
      data: {
        id: 'bp_b',
        component_key: 'node-b',
        component_type: 'form',
        component_id: 'form-schema-ab',
        name: 'Form B',
        prerequisites: ['node-a'],
        permitted_roles: [],
        input_mapping: {},
        sla_duration: { number: 0, unit: 'minutes' },
        approval_required: false,
        approval_roles: [],
      },
    },
    {
      id: 'node-c',
      type: 'form',
      position: { x: 200, y: 200 },
      data: {
        id: 'bp_c',
        component_key: 'node-c',
        component_type: 'form',
        component_id: 'form-schema-c',
        name: 'Form C',
        prerequisites: ['node-a'],
        permitted_roles: [],
        input_mapping: {},
        sla_duration: { number: 0, unit: 'minutes' },
        approval_required: false,
        approval_roles: [],
      },
    },
    {
      id: 'node-d',
      type: 'form',
      position: { x: 400, y: 0 },
      data: {
        id: 'bp_d',
        component_key: 'node-d',
        component_type: 'form',
        component_id: 'form-schema-ab',
        name: 'Form D',
        prerequisites: ['node-b'],
        permitted_roles: [],
        input_mapping: {},
        sla_duration: { number: 0, unit: 'minutes' },
        approval_required: false,
        approval_roles: [],
      },
    },
    {
      id: 'node-e',
      type: 'form',
      position: { x: 400, y: 200 },
      data: {
        id: 'bp_e',
        component_key: 'node-e',
        component_type: 'form',
        component_id: 'form-schema-c',
        name: 'Form E',
        prerequisites: ['node-c'],
        permitted_roles: [],
        input_mapping: {},
        sla_duration: { number: 0, unit: 'minutes' },
        approval_required: false,
        approval_roles: [],
      },
    },
    {
      id: 'node-f',
      type: 'form',
      position: { x: 600, y: 100 },
      data: {
        id: 'bp_f',
        component_key: 'node-f',
        component_type: 'form',
        component_id: 'form-schema-ab',
        name: 'Form F',
        prerequisites: ['node-d', 'node-e'],
        permitted_roles: [],
        input_mapping: {},
        sla_duration: { number: 0, unit: 'minutes' },
        approval_required: false,
        approval_roles: [],
      },
    },
  ],
  forms: [
    {
      id: 'form-schema-ab',
      name: 'shared form',
      description: '',
      is_reusable: true,
      field_schema: {
        type: 'object',
        properties: {
          email: { avantos_type: 'short-text', title: 'Email', type: 'string', format: 'email' },
          name: { avantos_type: 'short-text', title: 'Name', type: 'string' },
          button: { avantos_type: 'button', title: 'Button', type: 'object' },
        },
        required: ['email', 'name'],
      },
      ui_schema: {
        type: 'VerticalLayout',
        elements: [
          { type: 'Control', scope: '#/properties/email', label: 'Email' },
          { type: 'Control', scope: '#/properties/name', label: 'Name' },
        ],
      },
    },
    {
      id: 'form-schema-c',
      name: 'c-only form',
      description: '',
      is_reusable: false,
      field_schema: {
        type: 'object',
        properties: {
          notes: { avantos_type: 'multi-line-text', title: 'Notes', type: 'string' },
        },
        required: [],
      },
      ui_schema: {
        type: 'VerticalLayout',
        elements: [{ type: 'Control', scope: '#/properties/notes', label: 'Notes' }],
      },
    },
  ],
  branches: [],
  triggers: [],
} as unknown as BlueprintGraph;
